[package]
name = "openworkers-runtime"
version = "0.0.1"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
v8 = "0.75.1"
chrono = "0.4.28"
actix-web = "4"
env_logger = "0.10.0"
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
