[package]
name = "engine-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.68.0"
serde_v8 = "0.91.0"
base64 = "0.21.0"
