[package]
name = "engine-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.69.0"
actix-web = "4"
env_logger = "0.10.0"
